services:
  raiko-auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: raiko-auth
    container_name: raiko-auth
    ports:
      - "5001:8080"
      - "50051:50051"
    env_file:
      - ./.env
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true
